import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../../firebase";
import Navbar from "../../components/Navbar/Navbar";
import "./Impact.css";

function Impact() {
  const [metrics, setMetrics] = useState({
    totalListings: 0,
    itemsReused: 0,
    wasteSaved: 0,
    co2Saved: 0,
    categoryStats: {},
    recentActivity: [],
  });

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchImpactData = async () => {
      try {
        const querySnapshot = await getDocs(collection(db, "materials"));
        const allMaterials = querySnapshot.docs.map((doc) => ({
            id: doc.id,
            ...doc.data()
        }));

        // 1. Calculate Basic Counts
        const totalListings = allMaterials.length;
        
        // Items that are "unavailable" are considered REUSED/SOLD
        const soldItems = allMaterials.filter(item => item.status === "unavailable");
        const itemsReused = soldItems.length;

        // 2. Estimate Waste & CO2
        // Assumption: Average item weight = 5kg (since we don't have strict weight input yet)
        // Assumption: 1kg of waste recycled saves ~2.3kg of CO2
        const avgWeightPerItem = 5; 
        const wasteSaved = itemsReused * avgWeightPerItem;
        const co2Saved = (wasteSaved * 2.3).toFixed(1);

        // 3. Category Breakdown (Based on what was reused)
        const categoryStats = soldItems.reduce((acc, item) => {
          const cat = item.category || "Other";
          acc[cat] = (acc[cat] || 0) + 1;
          return acc;
        }, {});

        // 4. Recent Activity (Last 5 sold items)
        // We sort by createdAt if available, otherwise just take the list
        const recentActivity = soldItems
            .sort((a, b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0))
            .slice(0, 5);

        setMetrics({
          totalListings,
          itemsReused,
          wasteSaved,
          co2Saved,
          categoryStats,
          recentActivity
        });
        
        setLoading(false);
      } catch (err) {
        console.error("Error fetching impact data:", err);
        setLoading(false);
      }
    };

    fetchImpactData();
  }, []);

  if (loading) return <div className="loading">Calculating Impact...</div>;

  return (
    <>
      <Navbar />

      <div className="impact-container">
        <div className="impact-header">
            <h2>Environmental Impact Dashboard</h2>
            <p>Real-time metrics generated by our community</p>
        </div>

        {/* KPI CARDS */}
        <div className="impact-stats-grid">
          <div className="stat-card blue">
            <h3>{metrics.totalListings}</h3>
            <p>Total Listings Uploaded</p>
          </div>

          <div className="stat-card green">
            <h3>{metrics.itemsReused}</h3>
            <p>Items Reused / Sold</p>
          </div>

          <div className="stat-card orange">
            <h3>{metrics.wasteSaved} kg</h3>
            <p>Estimated Waste Diverted</p>
          </div>

          <div className="stat-card teal">
            <h3>{metrics.co2Saved} kg</h3>
            <p>CO₂ Emissions Prevented</p>
          </div>
        </div>

        <div className="impact-content-row">
            
            {/* LEFT: IMPACT BREAKDOWN */}
            <div className="impact-section">
                <h3>Why this matters</h3>
                <div className="impact-list">
                    <div className="impact-item">
                        <span className="icon">♻️</span>
                        <div>
                            <strong>Circular Economy</strong>
                            <p>Keeping materials in use instead of landfills.</p>
                        </div>
                    </div>
                    <div className="impact-item">
                        <span className="icon">🏭</span>
                        <div>
                            <strong>Reduced Production</strong>
                            <p>Lower demand for new raw material extraction.</p>
                        </div>
                    </div>
                    <div className="impact-item">
                        <span className="icon">🤝</span>
                        <div>
                            <strong>Community Power</strong>
                            <p>Connecting local supply with local demand.</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* RIGHT: CATEGORIES & ACTIVITY */}
            <div className="impact-section">
                <h3>Reused Materials by Category</h3>
                <div className="category-bars">
                    {Object.keys(metrics.categoryStats).length === 0 ? (
                        <p className="no-data">No items reused yet.</p>
                    ) : (
                        Object.keys(metrics.categoryStats).map((cat) => (
                            <div className="cat-row" key={cat}>
                                <span className="cat-name">{cat}</span>
                                <div className="bar-container">
                                    <div 
                                        className="bar-fill" 
                                        style={{width: `${(metrics.categoryStats[cat] / metrics.itemsReused) * 100}%`}}
                                    ></div>
                                </div>
                                <span className="cat-count">{metrics.categoryStats[cat]}</span>
                            </div>
                        ))
                    )}
                </div>

                <h3 style={{marginTop: '30px'}}>Recent Success Stories</h3>
                <ul className="activity-feed">
                    {metrics.recentActivity.length === 0 ? (
                        <li>No completed transactions yet.</li>
                    ) : (
                        metrics.recentActivity.map((item) => (
                            <li key={item.id}>
                                ✅ <strong>{item.name}</strong> was saved from landfill in {item.location || "Unknown Location"}
                            </li>
                        ))
                    )}
                </ul>
            </div>
        </div>
      </div>
    </>
  );
}

export default Impact;